version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install jq zip
  build:
    commands:
      - zip -r9 lambda_rng.zip index.js
      - aws s3api put-object --bucket lambda-builds-rng2 --key lambda_rng.zip --server-side-encryption aws:kms --body lambda_rng.zip > response.json
      - cat response.json
      - cat response.json | jq '{"Parameters":{"VersionId":.VersionId}}' > configuration.json
      - cat configuration.json
artifacts:
  files:
    - configuration.json
